-- ============================================================================
-- insert_data.sql
--
-- Purpose: Bulk-load the normalized CSVs (produced by src/preprocessing.py
--          and written to data/processed/) directly into Postgres using
--          COPY, as a faster alternative to the row-by-row / batched
--          INSERT approach in src/sql_connector.py.
--
-- Why COPY instead of INSERT for this step:
--   - COPY streams rows directly into the table in a single bulk operation,
--     bypassing the per-statement parsing/planning overhead of thousands
--     of individual INSERT statements.
--   - For a dataset this size (~10K rows), the difference is modest --
--     but the same pattern at the scale of a real retail company's
--     transaction table (10M+ rows) turns a multi-hour load into minutes.
--     Demonstrating awareness of this tradeoff is the point of including
--     both loading paths in this project.
--
-- Usage: run via psql (NOT a server-side script) so that \copy reads files
-- from the CLIENT machine's filesystem rather than requiring the CSVs to
-- exist on the database server itself:
--
--   psql -U postgres -d retail_analytics -f sql/insert_data.sql
--
-- Load order matches TABLE_LOAD_ORDER in src/sql_connector.py: every table
-- is loaded only after every table it has a foreign key to.
-- ============================================================================

BEGIN;

\copy regions (region_id, region_name) FROM 'data/processed/regions.csv' WITH (FORMAT csv, HEADER true);

\copy categories (category_id, category_name) FROM 'data/processed/categories.csv' WITH (FORMAT csv, HEADER true);

\copy locations (location_id, city, state, postal_code, region_id) FROM 'data/processed/locations.csv' WITH (FORMAT csv, HEADER true);

\copy sub_categories (subcategory_id, subcategory_name, category_id) FROM 'data/processed/sub_categories.csv' WITH (FORMAT csv, HEADER true);

\copy customers (customer_id, customer_name, segment) FROM 'data/processed/customers.csv' WITH (FORMAT csv, HEADER true);

\copy products (product_id, product_name, subcategory_id) FROM 'data/processed/products.csv' WITH (FORMAT csv, HEADER true);

\copy orders (order_id, order_date, ship_date, ship_mode, customer_id, location_id) FROM 'data/processed/orders.csv' WITH (FORMAT csv, HEADER true);

\copy sales (sales_id, order_id, product_id, sales, quantity, discount, profit) FROM 'data/processed/sales.csv' WITH (FORMAT csv, HEADER true);

-- ----------------------------------------------------------------------------
-- Reset SERIAL sequences after COPY.
--
-- COPY inserts explicit surrogate key values (e.g. region_id) generated by
-- preprocessing.py, rather than letting Postgres assign them via the
-- SERIAL default. This means each table's underlying sequence is NOT
-- automatically advanced -- without this step, the very next manual
-- INSERT (which relies on nextval()) would collide with an ID that COPY
-- already inserted. setval() re-synchronizes each sequence to MAX(id).
-- ----------------------------------------------------------------------------

SELECT setval('regions_region_id_seq', (SELECT MAX(region_id) FROM regions));
SELECT setval('categories_category_id_seq', (SELECT MAX(category_id) FROM categories));
SELECT setval('locations_location_id_seq', (SELECT MAX(location_id) FROM locations));
SELECT setval('sub_categories_subcategory_id_seq', (SELECT MAX(subcategory_id) FROM sub_categories));
SELECT setval('sales_sales_id_seq', (SELECT MAX(sales_id) FROM sales));

COMMIT;

-- Post-load sanity check: row counts per table, useful to eyeball against
-- the row counts logged by preprocessing.py to confirm nothing was dropped
-- silently during the COPY step.
SELECT 'regions' AS table_name, COUNT(*) FROM regions
UNION ALL SELECT 'locations', COUNT(*) FROM locations
UNION ALL SELECT 'customers', COUNT(*) FROM customers
UNION ALL SELECT 'categories', COUNT(*) FROM categories
UNION ALL SELECT 'sub_categories', COUNT(*) FROM sub_categories
UNION ALL SELECT 'products', COUNT(*) FROM products
UNION ALL SELECT 'orders', COUNT(*) FROM orders
UNION ALL SELECT 'sales', COUNT(*) FROM sales;
